CREATE TABLE IF NOT EXISTS "migrations" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "name" TEXT UNIQUE NOT NULL,
    "applied_at" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "seed_status" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "seeded" INTEGER NOT NULL DEFAULT 0, 
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)